### ISSUE TITLE
Exception trying to compile the dbldoo project

### ISSUE THREAD

**Issue by rvolosatovs** [Ruben-Sten/PP2LAL2PP#1]
`java -jar PP2LAL2PP.jar main.pp2` results in:

```
   Exception in thread "main" java.lang.ClassCastException: nl.rubensten.pp2lal2pp.lang.Value cannot be cast to nl.rubensten.pp2lal2pp.lang.Number
       at nl.rubensten.pp2lal2pp.compiler.Compiler.compile(Compiler.java:92)
       at nl.rubensten.pp2lal2pp.PP2LAL2PP.main(PP2LAL2PP.java:106)
```

**Comment by HannahSchellekens** [comment]
Could you embed your .pp2 source file?

**Comment by HannahSchellekens** [comment]
globals.pp2:

```
global sensor0 = getAnalog(INPUT_LIGHT_SENSOR)
global sensor1 = getAnalog(INPUT_LIGHT_SENSOR_BACKUP)
```

You can't use function calls in global variable declarations. Only numbers are supported.
